version: "3"

services:
  user-database:
    image: "postgres:latest"
    container_name: "user-database"
    ports:
      - "5432:5432"
    volumes:
      - userdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${DB_USERNAME}'"]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: "on-failure"

  cache-service:
    image: "redis:latest"
    container_name: "cache-service"
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'redis-cli PING'"]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: "on-failure"

volumes:
  userdata:
